# SITE CONFIGURATION
baseurl: ""
url: "https://prinzesschenpresswurst.github.io"

# SITE CONFIGURATION
theme: /_sass/my-theme.scss
title: Christin's homepage
description: The home of dog games
logo: /assets/img/logo.png