# SITE CONFIGURATION
baseurl: ""
url: "https://prinzesschenpresswurst.github.io"

# SITE CONFIGURATION
#theme: jekyll-theme-minimal
title: Christin's homepage
description: The home of dog games
logo: /assets/img/logo.png

